# Generated by Django 4.1.7 on 2023-04-13 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified_email_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.UUIDField(unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expiration',
            field=models.DateTimeField(verbose_name='Истечение срока'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified_email',
            field=models.BooleanField(default=False, verbose_name='Подтвержденный адрес эл. почты'),
        ),
    ]
