# Generated by Django 4.1.7 on 2023-05-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'Подтвержденный адрес эл. почты', 'verbose_name_plural': 'Подтвержденные адреса эл. почты'},
        ),
    ]
