services:
  web-shop:
    build: .
    volumes:
      - ./:/shop
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    environment:
      - DATABASE_HOST=database
      - DATABASE_NAME=dbname
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=pass
      - DATABASE_PORT=5432
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database


  database:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
      - DATABASE_PORT=5432

  redis:
    image: redis:6.0.16-alpine
    hostname: redis

  worker:
    build: .
    hostname: worker
    entrypoint: celery
    command: -A shop worker -l INFO
    volumes:
      - ./:/shop
    links:
      - redis
    depends_on:
      - redis
