services:

  database:
    image: postgres:15.2-alpine
    env_file:
      - ./.env.example

  web-shop:
    build: .
    volumes:
      - ./:/shop
    ports:
      - "8001:8000"
    env_file:
      - ./.env.example
    command: >
      sh -c "python3 manage.py migrate 
      && sleep 2s
      && python3 manage.py loaddata db_fixtures_docker.json
      && sleep 2s
      && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
      - redis

  redis:
    image: redis:6.0.16-alpine
    hostname: redis

  worker:
    build: .
    hostname: worker
    entrypoint: celery
    command: -A shop worker -l INFO
    volumes:
      - ./:/shop
    links:
      - redis
    depends_on:
      - redis
