# Generated by Django 4.1.7 on 2023-04-18 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0003_usersusedcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='user_used_coupon',
            field=models.ManyToManyField(through='coupons.UsersUsedCoupon', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи использовавшие купон'),
        ),
    ]
