# Generated by Django 4.1.7 on 2023-04-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='MainImage',
            field=models.ImageField(blank=True, upload_to='products_images', verbose_name='Главное изображение'),
        ),
    ]
