# Generated by Django 4.1.7 on 2023-04-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_mainimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='MainImage',
        ),
        migrations.AddField(
            model_name='product',
            name='MainImage',
            field=models.ImageField(blank=True, upload_to='products_images', verbose_name='Главное изображение'),
        ),
    ]
